<?php 
if(isset($_POST['timkiem'])){
    $text=$_POST['search1'];
    $text_lower=strtolower($text);
    switch($text_lower){
        case 'web' : header('location: index.html');
        break;
        case 'app' : header('location: 2.html');
        break;
        case 'os' : header('location: 3.html');
        break;  
        case 'lỗ hổng injection': header('location: index_copy.php?id=1');
        break;
        case 'lỗ hổng broken authentication': header('location: index_copy.php?id=2');
        break;
        case  'lỗ hổng cross site scripting' : header('location: index_copy.php?id=3');
        break;
        case  'xss' : header('location: index_copy.php?id=3');
        break;
        case 'lỗ hổng insecure direct object references': header('location: index_copy.php?id=4');
        break;
        case  'lỗ hổng security misconfiguration' : header('location: index_copy.php?id=5');
        break;
        case 'lỗ hổng sensitive data exposure ': header('location: index_copy.php?id=6');
        break;
        case 'lỗ hổng missing function level access control': header('location: index_copy.php?id=7');
        break;
        case  'xxe' : header('location: index_copy.php?id=7');
        break;
        case 'lỗ hổng cross site request forgery': header('location: index_copy.php?id=8');
        break;
        case 'csrf': header('location: index_copy.php?id=8');
        break;
        case 'lỗ hổng using component with known vulnerabilities': header('location: index_copy.php?id=9');
        break;      
        case 'lỗ hổng unvalidated redirects and forwards' : header('location: index_copy.php?id=10');
        break;
        case 'lỗ hổng injection attacks': header('location: index_copy.php?id=11');
        break;
        case 'lỗ hổng cross-site request forgery': header('location: index_copy.php?id=12');
        break;
        case 'csrf': header('location: index_copy.php?id=12');
        break;
        case  'lỗ hổng broken authentication' : header('location: index_copy.php?id=13');
        break;
        case 'lỗ hổng sensitive data exposure': header('location: index_copy.php?id=14');
        break;
        case  'lỗ hổng insecure direct object references' : header('location: index_copy.php?id=15');
        break;
        case  'idor' : header('location: index_copy.php?id=15');
        break;
        case 'lỗ hổng security misconfiguration ': header('location: index_copy.php?id=16');
        break;
        case 'lỗ hổng xml external entity attacks': header('location: index_copy.php?id=17');
        break;
        case  'xxe' : header('location: index_copy.php?id=17');
        break;
        case 'lỗ hổng insecure deserialization': header('location: index_copy.php?id=18');
        break;
        case 'lỗ hổng unvalidated redirects and forwards': header('location: index_copy.php?id=19');
        break;
        case 'lỗ hổng file upload vulnerabilities': header('location: index_copy.php?id=20');
        break;
        case 'lỗ hổng server-side request forgery' : header('location: index_copy.php?id=21');
        break;
        case  'ssrf' : header('location: index_copy.php?id=21');
        break;
        case 'lỗ hổng insecure cryptographic storage': header('location: index_copy.php?id=22');
        break;
        case  'lỗ hổng insufficient logging & monitoring' : header('location: index_copy.php?id=23');
        break;
        case 'lỗ hổng race conditions': header('location: index_copy.php?id=24');
        break;
        case  'lỗ hổng insecure api' : header('location: index_copy.php?id=25');
        break;
        case 'lỗ hổng tràn bộ đệm ': header('location: index_copy.php?id=26');
        break;
        case 'buffer overflow' : header('location: index_copy.php?id=26');
        break;
        case 'lỗ hổng nâng quyền hạn': header('location: index_copy.php?id=27');
        break;
        case  'privilege escalation' : header('location: index_copy.php?id=27');
        break;
        case 'lỗ hổng zero-day': header('location: index_copy.php?id=28');
        break;
        case 'lỗ hổng command injection': header('location: index_copy.php?id=29');
        break;
        case 'lỗ hổng path traversal': header('location: index_copy.php?id=30');
        break;
        case 'lỗ hổng phân quyền': header('location: index_copy.php?id=31');
        break;
        case  'permission issues' : header('location: index_copy.php?id=31');
        break;
        case 'lỗ hổng mã độc': header('location: index_copy.php?id=32');
        break;
        case  'malicious code vulnerabilities' : header('location: index_copy.php?id=32');
        break;
        case 'lỗ hổng quản lý phiên' : header('location: index_copy.php?id=33');
        break;
        case  'session management issues' : header('location: index_copy.php?id=33');
        break;
        case  'open source vulnerabilities' : header('location: index_copy.php?id=34');
        break;
        case 'lỗ hổng mã nguồn mở': header('location: index_copy.php?id=34');
        break;
        case 'lỗ hổng kiểm thử trên thiết bị di động': header('location: index_copy.php?id=35');
        break;
        case  'mobile device testing issues' : header('location: index_copy.php?id=35');
        break;
        case 'Lỗ hổng từ việc sử dụng dữ liệu không an toàn': header('location: index_copy.php?id=36');
        break;
        case 'insecure data storage' : header('location: index_copy.php?id=36');
        break;
        case 'Lỗ hổng từ việc sử dụng bộ nhớ không an toàn': header('location: index_copy.php?id=37');
        break;
        case  'insecure memory handling' : header('location: index_copy.php?id=37');
        break;
        case 'lỗ hổng từ việc sử dụng dịch vụ bên ngoài không an toàn': header('location: index_copy.php?id=38');
        break;
        case 'insecure external services' : header('location: index_copy.php?id=38');
        break;
        default : header('location: index_copy.php?id=-1');
        break ;
    }
}
?>